### ISSUE TITLE
Could you rename this repo to fishy?

### ISSUE THREAD

**Issue by unixorn** [sudorook/fishy-lite#1]
zsh-themes is a bit generic, especially since you only have one theme in the repo. 😄 

Also, please add a screen shot, I'd like to add a link to this theme to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) and it makes it easier for people to browse new themes if they don't have to install them to see what they look like.

**Comment by sudorook** [comment]
I'm kinda surprised you found this.

Your project is pretty ambitious. Lot's of information. It's a bit overwhelming, even. 

Anyway, I've renamed the repo and added a screenshot.

**Comment by unixorn** [comment]
Thanks!

**Comment by unixorn** [comment]
Will be added to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) by https://github.com/unixorn/awesome-zsh-plugins/pull/420
